let fourth = `
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

let second = `
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

let back = `




                     SSSSSSS

S

S
                                 
                                  SSSSSS



                     SSSSSSS



         SSSSSSSSS



  

SSSSS



SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS`;

let first = `
SSSSSSSSSSSSSSSSSSSSSSS



                SSSSSSS


    SSSSSSSSSS


                 SS


                        SS


        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                                 SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
`;

export const chars = {
  'F': first,
  'B': back,
  '2': second,
  '4': fourth
};


export const level = `
BB    BB    
BBFFFFBB
BBFFFFBB

`;
