let fourth = `
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

let second = `
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

let back = `


















SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS`;

let first = `
















        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

export const chars = {
  'F': first,
  'B': back,
  '2': second,
  '4': fourth
};


export const level = `
        
BBFFFF
BBFFFF

`;
