let fourth = `
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS
`;

let second = `

                                  SS






SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS

           SSSS                                   SSSSSS
    SSS

                    SSSSSSSSSSSSSSSSSSSSSS

     S


  S
      S
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS


        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                   SSSSS         SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS     SSSSSS         SSSSSSS












SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
`;

let back = `




                     SSSSSSS

S

S
                                 
                                  SSSSSS



                     SSSSSSS



         SSSSSSSSS



  

SSSSS



SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS`;

let first = `
SSSSSSSSSSSSSSSSSSSSSSS



                SSSSSSS


    SSSSSSSSSS


                 SS


                        SS


        @                                               SSSSSSS
     SSSSSSSSSSSSSSSSSS                                 SSSSSSS
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
`;

export const chars = {
  'F': first,
  'B': back,
  '2': second,
  '4': fourth
};


export const level = `
BB    
BBFFFF
BBFFFF222
      222
      222
      222
`;    
